prgrms-aibe-devcourse/AIBE1-Project2-Team05-frontend

Dockerfile

- 도커 파일 수정
- 작업 1:  `build:css` 명령을 사용하도록 도커 파일을 수정했습니다
- (선택사항)

[fix] 도커 파일 수정

---

public/community.html
public/includes/header.html
public/index.html
public/js/authHandler.js
public/js/community.js
public/js/include.js
public/match.html
public/mypage-mentee.html
public/mypage.html
public/register.html
src/routes/index.js
src/routes/proxy.js
src/server.js

- 프록시 서버 로직, 로그아웃 로직을 수정했습니다
- 작업 1: 프록시 서버로 전달시 제대로 전달되지 않는 오류가 있어 수정했습니다
- 작업 2: 로그아웃 시 async로 받아 서버의 요청을 대기하도록 변경했습니다
- (선택사항)

[fix] 프록시 서버, 로그아웃 수정

---

public/community.html
public/css/community.css
public/js/community.js
public/js/communityAPI.js
public/js/communityContants.js
public/js/communityRenderUtils.js

커뮤니티 페이지의 전체 프론트엔드 기능 구현
HTML 기본 구조 및 Tailwind CSS를 활용한 스타일링, API 연동을 통한 동적 데이터 바인딩 (게시글 목록, 인기글, 주간 인기글, 인기 태그), 상태 관리, 필터링(카테고리, 태그), 정렬, 검색, 페이지네이션 기능을 포함
각 기능은 모듈화된 JavaScript 파일들(`communityAPI.js`, `communityRenderUtils.js`, `communityConstants.js`, `community.js`)을 통해 구현되었으며, 사용자 인터랙션에 따른 동적인 UI 변경 및 데이터 표시를 지원
**1. HTML 구조 및 기본 스타일링 (`community.html`, `css/community.css`)**
* `feat(html): 커뮤니티 페이지 기본 DOM 구조 정의 및 초기 리소스(CSS/JS) 로드 설정`
* 메인 콘텐츠 영역, 사이드바, 게시글 목록, 인기글 섹션, 검색창, 필터 버튼 등 기본 레이아웃 구성.
* 동적 콘텐츠 표시를 위한 템플릿 (`postItemTemplate`, `weeklyPopularPostItemTemplate`) 및 플레이스홀더 정의.
* `feat(css): 커뮤니티 페이지용 커스텀 CSS 스타일 초기 규칙 세트 제공`
* Tailwind CSS와 함께 사용될 커스텀 스타일(페이지네이션, 카테고리/태그 버튼 등) 적용.
**2. 전역 상수 정의 (`js/communityConstants.js`)**
* `feat(constants): 애플리케이션 전역 상수(API URL, 페이지 설정 등) 초기 …

[feat] 커뮤니티 페이지 프론트엔드 전체 기능 구현

---

public/js/authHandler.js
public/js/include.js

- 로그아웃 로류수정
- 작업 1: 배포환경과 로컬환경이 달라 배포환경에 맞게 오류를 수정합니다
- (선택사항)

[fix] 로그아웃 수정

---

public/includes/header.html
public/js/authHandler.js

- 헤더/푸터 UI 플래시(깜빡임) 최소화
- 로그인/로그아웃 시 UI 전환 속도 개선
- 리프레시 토큰 발급 기준 및 로그인 상태 분기 로직 명확화
- 불필요한 서버 요청 제거 및 클라이언트 상태 기반 UI 처리
- 1. 헤더/푸터 로딩 방식 통일 및 초기 UI 개선
모든 페이지에서 헤더/푸터를 동일한 방식(id="header-placeholder", id="footer-placeholder")으로 로드하도록 통일
헤더의 로그인/회원가입 버튼이 기본적으로 보이도록 수정하여, 초기 로딩 시 사용자에게 자연스러운 UI 제공
- 2. 로그인/로그아웃 UI 플래시 최소화
authHandler.js에서 로그인 상태 체크 로직을 최적화하여, 불필요한 중복 체크와 서버 요청을 제거
세션스토리지(sessionStorage)에 로그인 정보가 있으면 즉시 로그아웃 UI를 보여주고, 없을 때만 서버에 쿠키(리프레시 토큰) 유무를 확인
- 3. 리프레시 토큰 발급 기준 명확화
세션스토리지에 로그인 정보가 없을 때만 /status 엔드포인트로 쿠키(리프레시 토큰) 유효성 확인
쿠키가 유효하면 리프레시 토큰을 통해 자동 로그인 처리 및 로그아웃 UI로 분기
쿠키가 없거나 만료되었으면 로그인 UI로 분기
- 4. 401 에러 처리 개선
API 호출 시 401 에러가 발생하면 /status로 리프레시 토큰 유효성 재확인
리프레시 토큰이 유효하면 자동으로 로그아웃 UI 유지, 만료 시 로그인 UI로 전환
불필요한 초기 서버 요청 제거
페이지 진입 시 매번 서버에 로그인 상태를 확인하지 않고, 클라이언트 상태(세션스토리지, 쿠키) …

[refactor] 로그인 로그아웃 로딩 시간 단축, 리프레시 토큰 발급 받는 기준 개선

---

public/js/authHandler.js
public/js/register.js

- 로그인/로그아웃 및 토큰 갱신(리프레시) 로직 개선
- 401 에러 발생 시 리프레시 토큰을 활용한 액세스 토큰 재발급 처리 추가
- 401 에러 처리 및 리프레시 토큰 활용
API 호출 시 401 에러가 발생하면 handle401Error()에서 익스프레스 서버에서 /status로 쿠키 여부를 확인
리프레시 토큰이 유효하면 refreshAccessToken()을 호출하여 /api/v1/auth/refresh로 액세스 토큰 재발급 시도
토큰 갱신 성공 시 로그인 UI 유지, 실패 시 로그아웃 UI로 전환
- (선택사항)

[refactor] 401 핸들러와 리프레시 토큰 합치기

---

public/mypage-mentee.html
public/mypage.html

- 마이페이지 활동 내역 탭 전반 UI를 백엔드 응답 구조에 맞춰 정리 (멘티 매칭 제외)
- 활동 내역 탭 내 주요 4개 섹션 UI 구조 정리
- 내가 등록한 재능
- 작성한 커뮤니티 게시글
- 작성한 댓글
- 관심 목록 (북마크 + 좋아요)

[feat] 마이페이지 활동 내역 탭 전반 UI 백엔드 응답 구조에 맞춰 정리 (멘티 매칭 제외)

---

public/js/authHandler.js
public/js/matching-type-selection.js
public/js/user-type-selection.js

- ai 매칭 api 연동
- 작업 1: ai 매칭 api 를 연동하고 멘토를 선택할 수 있는 기능을 추가했습니다
- (선택사항)

[feat] ai 매칭 api 연동

---

public/community-detail.html
public/community.html
public/js/api/apiClient.js
public/js/api/communityApi.js
public/js/community-detail.js
public/js/newPost.js

- 커뮤니티 검색 기능을 구현했습니다.
- 커뮤니티 게시글 상세 페이지의 전체 기능을 구현했습니다.
- 검색, 필터링, 상세 정보 표시, 댓글, 좋아요 등 모든 상호작용 기능을 포함합니다.
- 작업 1: 게시글 검색 기능
- 제목, 내용, 작성자별 검색 옵션 제공
- 드롭다운 기반 검색 타입 선택 UI
- 실시간 검색어 입력 및 검색 실행
- 검색 결과 즉시 렌더링
- 작업 2: 카테고리 필터링
- 전체, 질문/답변, 정보공유, 후기, 자유게시판, 재능나눔 카테고리 필터
- 카테고리 버튼 클릭 시 해당 게시글만 표시
- 선택된 카테고리 버튼 하이라이트 표시
- 작업 3: 게시글 상세 정보 표시
- 제목, 작성자, 작성일, 조회수, 카테고리, 태그 등 메타정보 렌더링
- 본문 내용 HTML 렌더링
- 프로필 이미지 표시 (메인 영역 및 사이드바)
- 작업 4: 이미지 갤러리 기능
- Supabase에서 가져온 이미지 URL 렌더링
- 단일/다중 이미지 레이아웃 자동 조정
- 이미지 클릭 시 모달로 확대 표시
- 이미지 로드 실패 시 placeholder 표시
- 작업 5: UX 개선
- 로딩 중 스켈레톤 UI 표시
- 에러 발생 시 사용자 친화적 메시지
- 모든 API 요청에 적절한 에러 핸들링
- 이미지 렌더링 시 null 체크 강화로 안정성 향상
- 네트워크 요청 실패 시 graceful degradation 적용
- 모든 사용자 액션에 대한 피드백 제공

[Feature] 커뮤니티 게시글 검색, 상세 페이지 구현

---

public/js/include.js

- 커뮤니티 관련 페이지(게시글 목록, 작성, 상세)에서 네비게이션 바 활성화 일관성 개선
- 작업 1: `include.js`의 `highlightActiveNavLink()` 함수 개선
- 커뮤니티 네비게이션 링크 활성화 로직 확장 (`newPost.html`, `community-detail.html` 페이지 포함)
- 매칭 페이지 네비게이션 인식 범위 확장 ('matching' 문자열 포함 페이지 대응)
- 작업 2: 네비게이션 바 하이라이트 테스트 및 검증
- 다양한 커뮤니티 페이지에서 일관된 네비게이션 경험 제공 확인
- 페이지 간 이동 시 활성 메뉴 유지 검증
이 PR은 사용자 경험 개선을 위한 것으로, 다음 이미지와 같이 커뮤니티 관련 모든 페이지에서 '커뮤니티' 메뉴가 하이라이트되도록 수정했습니다.
커뮤니티 목록 페이지에서만 네비게이션이 활성화되고, 글 작성이나 상세 페이지에서는 활성화되지 않는 문제가 있었습니다.
이제 모든 커뮤니티 관련 페이지에서 '커뮤니티' 메뉴가 활성화됩니다:
```
// 변경된 코드
else if (currentPage === 'community.html' || 
currentPage === 'newPost.html' || 
currentPage === 'community-detail.html') {
const communityLink = document.getElementById('nav-community');
if (communityLink) communityLink.className = activeClass;
}
```
이 개선으로 사용자가 커뮤니티 내에서 …

[Fix] 커뮤니티 페이지 네비게이션 일관성 개선

---

public/js/community.js

- 로컬 테스트용 API URL 제거
**## ✅ 체크리스트**

[fix] 로컬 API URL 제거

---

public/js/match.js

-   [x] 기능 추가
-   [ ] 버그 수정
-   [ ] 리팩토링
-   [ ] 문서 수정
-   [ ] 기타
-   **사용자가 매칭 신청에 성공했을 때, 현재 로그인된 사용자의 닉네임을 웹 브라우저의 `sessionStorage`에 저장하는 기능**을 추가했습니다.
-   이는 매칭 완료 후 다음 페이지 이동 시 사용자 정보를 활용하기 위함입니다.
-   `public/js/match.js` 파일에서 프로필 카드 클릭 이벤트 핸들러 내 로직을 수정했습니다.
-   매칭 신청 API 호출 결과 `status`가 `201`이고 `code`가 `"CREATED"`로 성공 응답을 받았을 경우, 추가적으로 `getCurrentUserInfo` 함수를 호출하여 현재 사용자 정보를 가져오도록 했습니다.
-   `getCurrentUserInfo` 함수는 `/api/v1/authUser/me` API를 `GET` 메소드로 호출하며, 필요한 헤더(`Content-Type: application/json`) 및 `credentials: "include"` 설정을 포함합니다.
-   API 응답 중 `status`가 `401`일 경우, 토큰 갱신을 시도하는 로직(`handle401Error`)을 포함하고, 실패 시 로그인 페이지로 리다이렉트하도록 처리했습니다. 그 외 API 요청 실패에 대해서도 예외 처리를 포함합니다.
-   `getCurrentUserInfo` 호출이 성공하여 `status`가 `200`이고 `code`가 `"SUCCESS"`이며 `data`가 존재하는 경우, **응답 …

[feat] 매칭 완료 후 세션 스토리지에 사용자 닉네임 저장 기능 구현

---

public/js/community-detail.js

-   [x] 기능 추가
-   [ ] 버그 수정
-   [x] 리팩토링
-   [ ] 문서 수정
-   [ ] 기타
-   **커뮤니티 상세 페이지의 좋아요 및 북마크 상태 관리 로직을 개선**했습니다.
-   페이지 로드 시 불필요한 API 호출을 줄이고, 사용자 인터랙션에 따른 UI 업데이트 정확도를 높여 **서버 상태와의 동기화를 강화**했습니다.
-   **페이지 로드 시 북마크 상태 확인 로직 제거:**
-   기존에 페이지 로드 시 별도로 호출되던 북마크 상태 확인 API (`/api/v1/community/{postId}/bookmark/status`) 호출 및 관련 함수(`checkBookmarkStatus`)를 제거했습니다.
-   이는 페이지 로딩 시 API 호출 횟수를 줄여 성능을 최적화하기 위함입니다.
-   **초기 상태 설정 방식 변경:**
-   이제 게시글 상세 정보를 불러오는 `loadPostDetail` 함수가 서버로부터 **현재 사용자의 `liked`(좋아요 여부) 및 `bookmarked`(북마크 여부) 상태를 함께 받아오도록 의존 관계를 변경**했습니다.
-   `renderPostDetail` 함수는 이 정보를 사용하여 페이지 로드 시 좋아요 및 북마크 아이콘의 초기 상태를 정확하게 설정합니다.
-   **(주의) 이 변경이 정상 동작하려면 백엔드의 게시글 상세 조회 API 응답에 `liked: boolean` 및 `bookmarked: boolean` 필드가 반드시 포함되어야 합니다.**
-   **좋아요 처리 로직(`handleLike`) 개선:**
- …

[feat] 좋아요/북마크 상태 관리 로직 개선

---

public/community-detail.html
public/js/community-detail.js

- 불필요한 코드(댓글 작성 폼 좌측 프로필 UI 및 업데이트 함수)를 제거했습니다.

[fix] 댓글 작성 폼 본인 프로필 이미지 UI 삭제

---

public/js/mypage-mentee.js
public/mypage-mentee.html

-   [x] 기능 추가
-   [ ] 버그 수정
-   [ ] 리팩토링
-   [ ] 문서 수정
-   [ ] 기타
-   **멘티 사용자를 위한 마이페이지 기본 구조 및 레이아웃(`mypage-mentee.html`)을 구현**했습니다.
-   마이페이지에 접속한 **사용자의 프로필 정보(이미지, 닉네임, 관심 분야, 지역, 소개글, 태그 등)를 화면에 표시**하는 기능을 추가했습니다.
-   **타인의 마이페이지 조회 시 '작성 리뷰' 및 '프로필 설정' 탭 버튼을 숨겨 접근 권한을 제어**하는 로직을 적용했습니다.
-   해당 사용자가 **작성한 멘티 리뷰 목록을 조회하여 화면에 표시**하는 기능을 구현했습니다.
-   **사용자 본인 여부를 확인하는 로직이 마이페이지 권한 처리 및 리뷰 내역 조회 시 활용**되도록 적용했습니다.
-   **`public/mypage-mentee.html` 파일을 통해 멘티 마이페이지의 기본 UI 구조(프로필 영역, 탭 메뉴, 각 탭 컨텐츠 영역)를 정의**했습니다.
-   **`public/js/mypage-mentee.js` 파일을 추가**하여 마이페이지 관련 동적 처리를 구현했습니다.
-   페이지 로드 시 **세션 스토리지에서 닉네임을 가져오거나 `/api/v1/users/{nickname}` API를 호출**하여 사용자 정보를 로드하고, 해당 정보로 프로필 영역을 업데이트합니다.
-   사용자 정보 로드 결과에 따라, 응답 데이터의 `me` 값을 확인하여 **`handleTabVisibility` 함수를 통해 '작성 리뷰'와 '프로필 설정' 탭의 표시 여부를 …

[feat] 마이페이지_멘티 사용자 프로필 표시, 권한 처리 및 리뷰 목록 기능 추가

---

public/community-detail.html
public/js/community-detail.js

- 커뮤니티 게시글 상세 페이지(community-detail.js)의 작성자 정보 표시, 댓글 시스템, 좋아요/북마크 기능 등을 DB 구조에 맞게 개선하고 여러 버그를 수정했습니다.
- DB 스키마 구조(`interest`, `introduction` 등)에 맞게 작성자 정보 표시 로직 수정
- 작성자 정보 영역 DOM 요소 ID 추가 및 일관성 있는 선택자 사용
- Interest enum 값을 사용자 친화적인 표시 형식으로 변환하는 함수 추가
- 작성자 소개글, 직업/직함 표시 로직 최적화
- 댓글 및 답글 날짜 표시 오류(1970-01-01) 수정 (null 값 처리)
- 댓글 작성 중 오류 발생 시 적절한 피드백 제공
- 임시 댓글 및 답글 UI 표시 로직 안정화
- DOM 요소를 찾지 못하는 오류 방지를 위한 안전 로직 추가
- 401 Unauthorized 오류 처리 로직 개선
- 요청 본문에 userId, communityId 필드 추가
- 백엔드 API 응답 형식에 맞게 요청 및 응답 처리 개선
- 로그인 세션 만료 상황에 대한 적절한 대응 추가
- 게시글 로드 실패 시 사용자 친화적인 오류 화면 표시
- API 호출 실패 시 적절한 토스트 메시지 표시
- 비로그인 사용자의 인터랙션 시 로그인 안내 메시지 표시
- 디버깅을 위한 포괄적인 콘솔 로그 추가
- 비동기 함수의 예외 처리 개선
- 코드 중복 최소화를 위한 함수 재구성
- 명확한 변수 및 함수 이름으로 가독성 향상
- 최신 JavaScript 기능 활용 (optional chaining, nullish coalescing 등)
- …

[Fix] 커뮤니티 게시글 상세 페이지의 작성자 정보 및 인터랙션 기능 개선

---

public/js/community-detail.js

- 북마크, 좋아요 URL, METHOD 변경
- POST, toggle 방식
method = isLiked ? 'DELETE' : 'POST'; -> method = 'POST'
method = isBookmarked ? 'DELETE' : 'POST'; -> method = 'POST'

[fix] 좋아요, 북마크 api url, method 수정

---

public/js/community-detail.js

- api 응답 명세와 불일치
- post에서 읽어온 좋아요,북마크 이름 변경
- 
- post.isLiked -> post.liked
- post.isBookmarked -> post.bookmarked

[fix] post에서 읽어온 좋아요,북마크 이름 수정

---

public/js/mypage-mentee.js
public/js/write-review.js
public/mypage-mentee.html
public/write-review.html
src/routes/pages.js

-   [x] 기능 추가
-   [ ] 버그 수정
-   [ ] 리팩토링
-   [ ] 문서 수정
-   [ ] 기타
-   멘티가 **작성 가능한 멘토링 세션 목록을 조회**하는 기능이 추가되었습니다.
-   멘티가 멘토링 세션에 대한 **리뷰를 작성**하는 기능이 추가되었습니다.
-   작성된 리뷰를 **수정하기 위해 기존 리뷰 정보를 조회**하는 기능이 추가되었습니다.
-   작성된 멘티 리뷰를 **수정**하는 기능이 추가되었습니다.
-   작성된 멘티 리뷰를 **삭제**하는 기능이 추가되었습니다.
-   특정 사용자의 멘티 **리뷰 내역을 조회**하는 기능이 추가되었습니다.
-   **작성 대상 멘토링 세션 조회**: 로그인한 멘티의 `COMPLETED` 상태 멘토링 세션 목록을 조회하는 `GET /v1/mentee/review` API가 구현되었습니다. `MentoringRepository`에 `findByMenteeIdAndStatus` 쿼리 메소드가 추가되었으며, 응답은 `MyCompletedMentoringDTO` 형태로 세션 ID와 멘토 이름이 반환됩니다. 이 기능은 리뷰 작성 페이지에서 사용됩니다.
-   **리뷰 작성**: `POST /v1/mentee/review` API를 통해 리뷰 작성이 가능합니다. 요청 시 `ReviewRequestDTO`에 세션ID, 제목, 내용, 별점(0.0~5.0), 관심사를 담아 전송합니다. 리뷰 중복 및 멘토링 세션 완료 상태, Bean Validation을 통한 유효성 검증 로직이 포함되어 있습니다. 
-   **리뷰 조회 (수정용)**: `GET …

[feat] 작성 리뷰 페이지 리뷰 조회 작성 수정 삭제 기능 구현

---

public/js/more-details.js
public/js/mypage.js
public/mypage.html

- 마이페이지 매칭 현황 및 더보기 중간 커밋 (배포 테스트용)
- 작업 1: 마이페이지 매칭 현황
- 작업 2: 매칭 현황 더보기 일부

[feat] 마이페이지 매칭 현황 및 더보기 중간 커밋

---

public/js/more-details.js
public/js/my-interests.js
public/more-details.html
public/mypage-mentee.html
public/mypage.html

- 마이페이지 나의 활동 내역 관심 목록 더보기
- 작업 1: 마이페이지 나의 활동 내역 관심 목록 더보기 api 연동
- 작업 2: 마이페이지 나의 활동 내역 관심 목록 더보기 필터 처리 all | bookmarked | liked

[feat] 마이페이지 나의 활동 내역 관심 목록 더보기

---

public/js/my-talents.js
public/more-details.html

- 마이페이지 "내가 등록한 재능" 더보기 기능 구현 및 API 연동
- 작업 1: /more-details?type=my-talents 경로에서 내가 등록한 재능 목록 불러오기
- 작업 2: my-talents.js 신규 생성 및 API 연동 로직 구현
- 작업 3: 날짜 포맷 적용 (createdAt → YYYY. M. D. 형식으로 표시)
- 작업 4: 중복 필터 제거 및 콘텐츠 카드 UI 구성
- 현재는 페이징 미구현 (최대 10개만 출력), 추후 확장 예정

[feat] 마이페이지 내가 등록한 재능 더보기 API 연동 및 날짜 포맷 적용

---

public/js/interest-qna.js
public/more-details.html
public/mypage.html

- 마이페이지 매칭 현황 > 커뮤니티 질문/답변 더보기 탭 API 연동 및 렌더링 구현
- 작업 1: /more-details.html?type=interest-qna 진입 시 추천 질문/답변 게시글 출력
- 작업 2: interest-qna.js 파일 생성 및 게시글 카드 렌더링 구현
- 제목, 작성자 닉네임/이미지, 태그, 댓글 수, 작성일 표시
- 작업 3: 카드 클릭 시 상세 페이지로 이동 예정 (현재는 미구현)

[feat] 마이페이지 매칭 현황 커뮤니티 질문 답변 더보기

---

public/js/mypage-activity.js
public/mypage-mentee.html
public/mypage.html

- 마이페이지의 나의 활동 내역을 추가했습니다
- 작업 1: 멘토
나의 재능 목록, 내가 작성한 게시글, 내가 작성한 댓글 , 나의 관심 목록 기능을 추가했습니다
- 작업 2: 멘티
나의 매칭 현황, 내가 작성한 게시글, 내가 작성한 댓글 , 나의 관심 목록 기능을 추가했습니다
- (선택사항)

[feat] 마이페이지 나의 활동내역

---

public/mypage-mentee.html
public/mypage.html

- 관심 목록 더보기 잘못 설정된 경로 수정
- 관심 목록 더보기 잘못 설정된 경로 수정

[fix] 관심 목록 더보기 잘못 설정된 경로 수정

---

public/js/mypage-mentee.js
public/js/mypage.js
public/mypage-mentee.html
public/mypage.html

- 마이페이지 프로필 중복 호출 수정
- 작업 1: 마이페이지 파일에서 프로필을 중복호출하여 프로필이 불러와지지 않는 오류가 발생해 수정하였습니다
- (선택사항)

[fix] 프로필 설정 mypage.js 와 mypage-mentee.js 파일 충돌 해결

---

public/js/mypage.js
public/js/ongoing.js
public/more-details.html
public/mypage.html

- 진행 중 매칭 더보기 페이지 API 연동 및 카드 UI 구현
- /v1/users/{nickname}/matching/more-details?type=ongoing API와 연동하여 데이터 렌더링
- 프로필 이미지, 닉네임, 매칭 날짜, 카테고리, 소개글, 태그, 연락하기 버튼 포함
- 마이페이지 미리보기 섹션과 동일한 UI 구성 유지
- 현재는 필터링 없이 전체 매칭 리스트 출력됨 (진행중/완료 구분 없이 노출)
- 백엔드 필터링 로직 추가 후 클라이언트 필터 적용 예정

[feat] 진행 중 매칭 더보기 API 연동 및 UI 렌더링 구현

---

public/js/more-details/common-pagination.js
public/js/mypage-activity.js
public/mypage-mentee.html
public/mypage.html

[refactor] 페이지네이션 컴포넌트 스타일 및 UI 통일

---

public/js/more-details/my-matches.js
public/login.html
public/register.html

[fix] 매칭 종료 API 엔드포인트 및 요청 형식 수정

---

public/js/mypage-mentee.js
public/js/write-review.js
public/mypage-mentee.html

[feat] 리뷰에서 name 대신 nickname 사용으로 변경
